// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzxmsjqfudoohmathtam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6eG1zanFmdWRvb2htYXRodGFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Mzg2MDQsImV4cCI6MjA3MzQxNDYwNH0.SZX3HrTtX8BN7VjN8yDVoSSB_yfWD0hew3NSB5kTXmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});